### ISSUE TITLE
Can't send traversals

### ISSUE THREAD

**Issue by LuisBosquez** [PommeVerte/gremlin-php#43] opened 2017-10-23 20:03 UTC
I am connecting to an Azure Cosmos DB gremlin endpoint, but it seems like I can't send any queries.

This is my code:
```
require_once('vendor/autoload.php');
use \Brightzone\GremlinDriver\Connection;

echo "starting\n";
$db = new Connection;
$db = new Connection([
    'host' => '',
    'username' => '',
    'password' => ''
    ,'graph' => ''
    ,'port' => '443'
]);

$db->timeout = 0.5; 

try {
    echo "Attempting to connect\n";
    $db->open();
    echo "Connected, sending query:\n";
    $result = $db->send('g.V(1)');
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}

//do something with result
echo "printing result\n";
print_r($result);

$db->close();

```

This is the result I am getting:
    
```
starting
Attempting to connect
PHP Notice:  Undefined offset: 1 in D:\Projects\azure-cosmos-db-php-sample\vendor\brightzone\gremlin-php\src\Connection.php on line 215
Connected, sending query:
PHP Warning:  Parameter 1 to Brightzone\GremlinDriver\Connection::Brightzone\GremlinDriver\{closure}() expected to be a reference, value given in D:\Projects\azure-cosmos-db-php-sample\vendor\brightzone\gremlin-php\src\Workload.php on line 78
PHP Notice:  Undefined offset: 1 in D:\Projects\azure-cosmos-db-php-sample\vendor\brightzone\gremlin-php\src\Connection.php on line 236
```
1. What does the `Undefined offset: 1` error mean? 
2. Why do these warnings stop the execution of the program? I am not seeing any errors/exceptions being thrown at the try/catch.
3. I didn't find this in the documentation. Does this driver implement the RemoteServer connection protocol?

**Comment by The-Don-Himself** [comment] 2017-12-31 23:42
Hi @LuisBosquez are you still facing this issue? I'd be happy to help you resolve it and close this issue since it's the only open issue heading into the New Year.

**Comment by dkusmierek** [comment] 2018-04-09 16:37
Hi @The-Don-Himself ;) I started using this library a couple days ago and met the same problem. This problem occurs from the PHP 7 version. Before everything was great. Is it possible to solve this problem soon? I'd like to use this library for our current project but It's not possible at this point. 

I checked this and the problem is with "send" function (Connection:472) where the instance of Workload is created.

**Comment by PommeVerte** [comment] 2018-04-09 17:06
Hey there.

I think these might be different issues. Luis mostly highlighted an error that did not reflect the underlying problem. 
In your case I think it's a php 7 compatibility problem. Can you tell me what your version of php7 is so that be sure to test it?

**Comment by dkusmierek** [comment] 2018-04-09 17:28
Thanks for so quick response ;) There is PHP 7.2

**Comment by The-Don-Himself** [comment] 2018-04-09 21:17
@dkusmierek I wrote a small [library](https://github.com/The-Don-Himself/gremlin-ogm) on top of this one. I successfully tested it with CosmosDB, my last test was with PHP 7.1.x, I plan to test it with PHP 7.2.x but I don't have access a ready instance right now. If you do, it only takes 5mins.

**Comment by juhasev** [comment] 2018-04-10 21:37
@ dkusmierek I am having a same issue here with PHP 7.2

Brightzone\GremlinDriver\InternalException: gremlin-php driver has thrown the following error : Parameter 1 to Brightzone\GremlinDriver\Connection::Brightzone\GremlinDriver\{closure}() expected to be a reference, value given

/home/vagrant/Code/platform/vendor/brightzone/gremlin-php/src/Connection.php:791
/home/vagrant/Code/platform/vendor/brightzone/gremlin-php/src/Connection.php:485

**Comment by PommeVerte** [comment] 2018-04-10 21:38
I will be fixing this and pushing changes tomorrow.

**Comment by PommeVerte** [comment] 2018-04-12 03:07
I'm still working to recreate the issue. 7.2.4 works fine right now. I'm going to try the other 7.2.x versions and also change the error reporting to see if I get anything

**Comment by PommeVerte** [comment] 2018-04-12 03:36
7.2.0 works fine as well. My reporting was set with `E_ALL` as well. 
Are you all using version 3.0.2 of `gremlin-php`?

I remember fixing this issue a while back somehow

**Comment by PommeVerte** [comment] 2018-04-17 05:53
The original issue has also been fixed here. Version 3.1.0 is out.

Cheers all.

**Closed by PommeVerte** 2018-04-17 05:53 UTC
